services:
  backend:
    image: 692137657571.dkr.ecr.us-west-1.amazonaws.com/sportshub-backend:latest
    container_name: sportshub-backend
    restart: unless-stopped

    env_file:
      - ./backend/.env

    environment:
      DATABASE_URL: sqlite:////app/instance/sportshub.db

    volumes:
      - backend_data:/app/instance

    ports:
      - "5000:5000"

  frontend:
    image: 692137657571.dkr.ecr.us-west-1.amazonaws.com/sportshub-frontend:latest
    container_name: sportshub-frontend
    restart: unless-stopped

    depends_on:
      - backend

    ports:
      - "80:80"

volumes:
  backend_data:
